# # terraform-docs version constraints for execution
# # more information: https://terraform-docs.io/user-guide/configuration/#version
# version: ">= 0.10, < 0.12"

formatter: markdown table

header-from: doc.txt
footer-from: footer.md

sections:
  show:
    - header
    - inputs
    - providers
    - modules
    - footer

# output:
#   file: README.md
#   mode: inject
#   template: |-
#     <!-- BEGIN_TF_DOCS -->
#     The template can be customized with aribitrary markdown content.
#     For example this can be shown before the actual content generated
#     by formatters.

#     {{ .Content }}

#     You can also show something after it!
#     <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
