name: prerelease

on:
  push:
    tags:
      - "v*.*.*-*"

env:
  GO_VERSION: "1.21.5"
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  prerelease:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: env.REGISTRY_USERNAME != ''
        with:
          version: latest
          args: release --rm-dist --skip-publish --skip-sign

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/terraform-docs-v*
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:11} # tag name without leading 'v'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        if: env.REGISTRY_USERNAME != ''
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/${{ env.REPO_OWNER }}/terraform-docs:${{ steps.vars.outputs.tag }}
